'use strict';
/**
 * Detection Rules Canonical Store Manager
 * Manages the central repository of Sigma/YARA/Suricata/KQL/Splunk/OSQuery rules.
 *
 * Every rule generated by Sentinel-APEX Detection Engine flows through here:
 * - Validates against schema
 * - Assigns unique rule ID + version
 * - Stores with governance metadata (confidence, source, analyst status)
 * - Maintains change history for versioning
 * - Links to source IOCs, techniques, campaigns
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const CANONICAL_PATH = path.join(__dirname, '..', '..', 'data', 'detection-rules-canonical.json');

/**
 * Generate deterministic rule ID from content
 * Same rule content = same ID (enables deduplication)
 */
function generateRuleId(spec) {
  const content = JSON.stringify({
    technique_id: spec.technique_id,
    title: spec.title,
    level: spec.level,
    platforms: Object.keys(spec).filter(k => ['sigma', 'kql', 'splunk', 'osquery'].includes(k)),
  });
  return crypto.createHash('sha256').update(content).digest('hex').slice(0, 16);
}

/**
 * Load canonical rule store from disk
 */
function loadCanonical() {
  try {
    const data = fs.readFileSync(CANONICAL_PATH, 'utf8');
    return JSON.parse(data);
  } catch (e) {
    return { meta: { version: '1.0.0', generated: new Date().toISOString(), total_rules: 0 }, rules: [] };
  }
}

/**
 * Save canonical rule store to disk (atomic write)
 */
function saveCanonical(store) {
  const tmp = CANONICAL_PATH + '.tmp';
  try {
    fs.writeFileSync(tmp, JSON.stringify(store, null, 2), 'utf8');
    fs.renameSync(tmp, CANONICAL_PATH);
    return true;
  } catch (e) {
    try { fs.unlinkSync(tmp); } catch (_) {}
    console.error('[DETECTION RULES] Failed to save canonical store:', e.message);
    return false;
  }
}

/**
 * Store a generated detection rule in the canonical store
 * Called after detection engine generates Sigma/YARA/KQL rules
 */
function storeRule(ruleSpec, sourceMetadata = {}) {
  if (!ruleSpec || !ruleSpec.technique_id || !ruleSpec.title) {
    throw new Error('Detection rule must have technique_id and title');
  }

  const store = loadCanonical();
  const ruleId = generateRuleId(ruleSpec);

  // Check if rule already exists
  const existingIdx = store.rules.findIndex(r => r.id === ruleId);
  const timestamp = new Date().toISOString();

  const canonicalRule = {
    id: ruleId,
    technique_id: ruleSpec.technique_id,
    title: ruleSpec.title,
    level: ruleSpec.level,
    description: ruleSpec.description || '',
    data_source: ruleSpec.data_source || '',

    // Rule formats (Sigma/KQL/Splunk/OSQuery/Suricata)
    platforms: {
      sigma: ruleSpec.sigma || null,
      kql: ruleSpec.kql || null,
      splunk: ruleSpec.splunk || null,
      osquery: ruleSpec.osquery || null,
    },
    suricata: ruleSpec.suricata || [],

    // Governance & Metadata
    governance: {
      status: 'GENERATED', // GENERATED → REVIEW → APPROVED → PUBLISHED
      confidence: sourceMetadata.confidence || 'MEDIUM',
      created_at: existingIdx === -1 ? timestamp : store.rules[existingIdx].governance.created_at,
      updated_at: timestamp,
      version: existingIdx === -1 ? '1.0.0' : incrementVersion(store.rules[existingIdx].governance.version),
    },

    // Source tracking
    source: {
      iocs: sourceMetadata.iocs || [],
      articles: sourceMetadata.articles || [],
      campaigns: sourceMetadata.campaigns || [],
      evidence: sourceMetadata.evidence || '',
    },

    // Change history
    history: existingIdx === -1
      ? [{ version: '1.0.0', timestamp, change: 'Rule generated', author: 'detection-engine' }]
      : [...store.rules[existingIdx].history, {
          version: incrementVersion(store.rules[existingIdx].governance.version),
          timestamp,
          change: sourceMetadata.change || 'Rule updated',
          author: sourceMetadata.author || 'detection-engine'
        }],
  };

  if (existingIdx === -1) {
    store.rules.push(canonicalRule);
  } else {
    store.rules[existingIdx] = canonicalRule;
  }

  store.meta.total_rules = store.rules.length;
  store.meta.generated = timestamp;

  saveCanonical(store);
  return canonicalRule;
}

/**
 * Increment semantic version (1.0.0 → 1.0.1 → 1.0.2 or 1.1.0 for minor)
 */
function incrementVersion(version) {
  const parts = version.split('.').map(Number);
  parts[2] = (parts[2] || 0) + 1; // Increment patch
  return parts.join('.');
}

/**
 * Store multiple rules (batch operation from detection engine)
 */
function storeRules(ruleSpecs, sourceMetadata = {}) {
  const stored = [];
  for (const spec of (ruleSpecs || [])) {
    try {
      const rule = storeRule(spec, sourceMetadata);
      stored.push(rule);
    } catch (e) {
      console.error(`[DETECTION RULES] Failed to store rule ${spec.technique_id}:`, e.message);
    }
  }
  return stored;
}

/**
 * Get rule by ID
 */
function getRule(ruleId) {
  const store = loadCanonical();
  return store.rules.find(r => r.id === ruleId) || null;
}

/**
 * Get rules by technique ID (may be multiple versions)
 */
function getRulesByTechnique(techniqueId) {
  const store = loadCanonical();
  return store.rules.filter(r => r.technique_id === techniqueId);
}

/**
 * Get rules by governance status (GENERATED, REVIEW, APPROVED, PUBLISHED)
 */
function getRulesByStatus(status) {
  const store = loadCanonical();
  return store.rules.filter(r => r.governance.status === status);
}

/**
 * Update rule governance status (e.g., GENERATED → APPROVED → PUBLISHED)
 */
function updateRuleStatus(ruleId, newStatus, metadata = {}) {
  const store = loadCanonical();
  const idx = store.rules.findIndex(r => r.id === ruleId);
  if (idx === -1) throw new Error(`Rule not found: ${ruleId}`);

  const rule = store.rules[idx];
  const oldStatus = rule.governance.status;

  rule.governance.status = newStatus;
  rule.governance.updated_at = new Date().toISOString();

  rule.history.push({
    version: rule.governance.version,
    timestamp: rule.governance.updated_at,
    change: `Status changed: ${oldStatus} → ${newStatus}`,
    author: metadata.author || 'system',
    comment: metadata.comment || '',
  });

  saveCanonical(store);
  return rule;
}

/**
 * Search rules with filters
 */
function searchRules(filters = {}) {
  const store = loadCanonical();
  let results = store.rules;

  if (filters.technique_id) {
    results = results.filter(r => r.technique_id === filters.technique_id);
  }
  if (filters.level) {
    results = results.filter(r => r.level === filters.level);
  }
  if (filters.status) {
    results = results.filter(r => r.governance.status === filters.status);
  }
  if (filters.platform) {
    results = results.filter(r => r.platforms[filters.platform] !== null);
  }
  if (filters.confidence) {
    results = results.filter(r => r.governance.confidence === filters.confidence);
  }
  if (filters.query) {
    const q = filters.query.toLowerCase();
    results = results.filter(r =>
      r.title.toLowerCase().includes(q) ||
      r.description.toLowerCase().includes(q) ||
      r.technique_id.toLowerCase().includes(q)
    );
  }

  return results;
}

/**
 * Get rule version history
 */
function getRuleHistory(ruleId) {
  const rule = getRule(ruleId);
  if (!rule) return null;
  return rule.history;
}

/**
 * Export rules in specific format (for download)
 */
function exportRules(format = 'json', filters = {}) {
  const rules = searchRules(filters);

  if (format === 'json') {
    return JSON.stringify({ rules, count: rules.length }, null, 2);
  }

  if (format === 'sigma') {
    // Export as concatenated Sigma YAML
    return rules
      .filter(r => r.platforms.sigma)
      .map(r => r.platforms.sigma)
      .join('\n---\n');
  }

  if (format === 'kql') {
    // Export as KQL queries (concat with OR)
    const queries = rules.filter(r => r.platforms.kql).map(r => `(${r.platforms.kql})`);
    return queries.join('\n| OR ');
  }

  if (format === 'suricata') {
    // Export as Suricata rules
    return rules
      .flatMap(r => r.suricata || [])
      .join('\n');
  }

  if (format === 'csv') {
    // CSV export for spreadsheet analysis
    const header = 'Rule ID,Technique ID,Title,Level,Status,Platform Count,Last Updated\n';
    const rows = rules.map(r =>
      `${r.id},${r.technique_id},"${r.title.replace(/"/g, '""')}",${r.level},${r.governance.status},` +
      `${Object.values(r.platforms).filter(v => v !== null).length},${r.governance.updated_at}`
    );
    return header + rows.join('\n');
  }

  throw new Error(`Unknown export format: ${format}`);
}

/**
 * Get statistics about the rule store
 */
function getStats() {
  const store = loadCanonical();
  const statuses = {};
  const levels = {};
  const platforms = { sigma: 0, kql: 0, splunk: 0, osquery: 0, suricata: 0 };
  const techniques = new Set();

  for (const rule of store.rules) {
    statuses[rule.governance.status] = (statuses[rule.governance.status] || 0) + 1;
    levels[rule.level] = (levels[rule.level] || 0) + 1;
    techniques.add(rule.technique_id);

    if (rule.platforms.sigma) platforms.sigma++;
    if (rule.platforms.kql) platforms.kql++;
    if (rule.platforms.splunk) platforms.splunk++;
    if (rule.platforms.osquery) platforms.osquery++;
    if (rule.suricata?.length) platforms.suricata++;
  }

  return {
    total_rules: store.rules.length,
    unique_techniques: techniques.size,
    statuses,
    levels,
    platforms,
    last_updated: store.meta.generated,
  };
}

module.exports = {
  storeRule,
  storeRules,
  getRule,
  getRulesByTechnique,
  getRulesByStatus,
  updateRuleStatus,
  searchRules,
  getRuleHistory,
  exportRules,
  getStats,
  loadCanonical,
  saveCanonical,
};
