/**
 * SENTINEL APEX — Intel Data Loader + Tier-Based Content Filter
 * Reads from static JSON files generated by the pipeline.
 * Phase 4: Paid Intel Segmentation — enforces Free/Pro/Enterprise access.
 * Phase 7: Trust & Verification — source attribution + confidence on every item.
 */
'use strict';
const fs   = require('fs');
const path = require('path');

// Paths to static intel files (generated by fetch-live-intel.js)
const BASE = path.resolve(__dirname, '../../');
const PATHS = {
  live:        path.join(BASE, 'api', 'intel', 'live.json'),
  topThreats:  path.join(BASE, 'api', 'intel', 'top-threats.json'),
  iocs:        path.join(BASE, 'api', 'intel', 'iocs.json'),
  ransomware:  path.join(BASE, 'api', 'intel', 'ransomware.json'),
  liveWidget:  path.join(BASE, 'live-intel.json'),
  state:       path.join(BASE, 'intel-state.json'),
};

let _cache = {};
let _cacheTime = {};
const CACHE_TTL_MS = 60000; // 1-minute in-process cache

function loadJSON(filePath) {
  const now = Date.now();
  if (_cache[filePath] && (now - (_cacheTime[filePath] || 0)) < CACHE_TTL_MS) {
    return _cache[filePath];
  }
  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(raw);
    _cache[filePath] = data;
    _cacheTime[filePath] = now;
    return data;
  } catch (e) {
    console.error(`[INTEL] Failed to load ${filePath}: ${e.message}`);
    return null;
  }
}

// Trust & Verification: Ensure every item has required attestation fields
function attestItem(item) {
  return {
    ...item,
    _trust: {
      source_attribution:  item.source || item.sources || 'SENTINEL APEX v4.0',
      confidence_score:    item.sourceCount >= 2 ? 0.95 : item.cisaKev ? 0.98 : 0.82,
      correlation_count:   item.sourceCount || 1,
      verified_at:         new Date().toISOString(),
      methodology:         'Multi-source correlation, CVSS scoring, KEV verification, IOC extraction',
      platform:            'CYBERDUDEBIVASH SENTINEL APEX v4.0',
    },
  };
}

// FREE tier: remove sensitive fields, limit depth
function filterFree(item) {
  const { iocs, ioc_count, refs, cves, ...safe } = item;
  return {
    id:             safe.id,
    title:          safe.title,
    description:    safe.description ? safe.description.slice(0, 150) + '…  [Upgrade to Pro for full details]' : '',
    cvss:           safe.cvss,
    threat_level:   safe.threat_level,
    type:           safe.type,
    published:      safe.published,
    exploited:      safe.exploited,
    cisa_kev:       safe.cisa_kev,
    vendor:         safe.vendor,
    product:        safe.product,
    priority_score: safe.priority_score,
    sources_confirmed: safe.sources_confirmed,
    _upgrade:       'Full IOCs, MITRE mapping, Sigma/YARA rules, and attack chain available on Pro plan — https://blog.cyberdudebivash.in/pricing.html',
    _trust:         (safe._trust || attestItem(safe)._trust),
  };
}

// PRO tier: full data except raw file access
function filterPro(item) {
  return attestItem({
    ...item,
    description: item.description,
    iocs:        (item.iocs || []).slice(0, 50),
    refs:        (item.refs || []).slice(0, 10),
    cves:        item.cves || [],
    report_url:  item.report_url || null,
  });
}

// ENTERPRISE tier: everything
function filterEnterprise(item) {
  return attestItem(item);
}

function applyTierFilter(items, tier) {
  switch (tier) {
    case 'enterprise': return items.map(filterEnterprise);
    case 'pro':        return items.map(filterPro);
    default:           return items.map(filterFree);
  }
}

// Parse + validate pagination params
function parsePagination(query) {
  const page  = Math.max(1, parseInt(query.page || '1', 10));
  const limit = Math.min(100, Math.max(1, parseInt(query.limit || '25', 10)));
  return { page, limit, offset: (page - 1) * limit };
}

// Apply filters from query params
function applyFilters(items, query) {
  let out = [...items];

  if (query.severity) {
    const sev = query.severity.toUpperCase();
    out = out.filter(i => (i.threat_level || '').toUpperCase() === sev);
  }
  if (query.type) {
    const t = query.type.toUpperCase();
    out = out.filter(i => (i.type || '').toUpperCase() === t);
  }
  if (query.exploited === 'true' || query.exploited === '1') {
    out = out.filter(i => i.exploited);
  }
  if (query.cisa_kev === 'true' || query.cisa_kev === '1') {
    out = out.filter(i => i.cisa_kev);
  }
  if (query.min_cvss) {
    const min = parseFloat(query.min_cvss);
    out = out.filter(i => (i.cvss || 0) >= min);
  }
  if (query.from_date) {
    const from = new Date(query.from_date);
    out = out.filter(i => new Date(i.published || 0) >= from);
  }
  if (query.vendor) {
    const v = query.vendor.toLowerCase();
    out = out.filter(i => (i.vendor || '').toLowerCase().includes(v));
  }
  return out;
}

// Main intel loader — used by all endpoints
function getIntel(type, tier, query = {}) {
  const file = PATHS[type] || PATHS.live;
  const data = loadJSON(file);
  if (!data) return { items: [], total: 0, cached: false, error: 'Intel source temporarily unavailable' };

  const raw = data.items || [];
  const filtered = applyFilters(raw, query);
  const { page, limit, offset } = parsePagination(query);
  const paged = filtered.slice(offset, offset + limit);
  const tiered = applyTierFilter(paged, tier);

  return {
    items: tiered,
    pagination: {
      page,
      limit,
      total:       filtered.length,
      total_pages: Math.ceil(filtered.length / limit),
      has_next:    offset + limit < filtered.length,
      has_prev:    page > 1,
    },
    intel_meta: {
      generated_at:    data.generated || data.generatedAt || null,
      total_published: data.total_published || data.totalPublished || 0,
      source_platform: data.source || 'CYBERDUDEBIVASH SENTINEL APEX v4.0',
    },
    tier_info: {
      tier,
      full_access:       tier !== 'free',
      ioc_access:        tier !== 'free',
      detection_rules:   tier !== 'free',
      realtime_feed:     tier === 'enterprise',
      upgrade_url:       tier !== 'enterprise' ? 'https://blog.cyberdudebivash.in/pricing.html' : null,
    },
  };
}

// CVE detail lookup across all intel files
function getCVEDetail(cveId, tier) {
  const normalized = cveId.toUpperCase().trim();
  // Try dedicated CVE file first
  const cvePath = path.join(BASE, 'api', 'intel', 'cve', `${normalized}.json`);
  if (fs.existsSync(cvePath)) {
    const data = loadJSON(cvePath);
    if (data) {
      const item = tier === 'enterprise' ? filterEnterprise(data)
                  : tier === 'pro'        ? filterPro(data)
                  : filterFree(data);
      return { found: true, item: attestItem(item) };
    }
  }
  // Fall back to scanning live feed
  const live = loadJSON(PATHS.live);
  if (live && live.items) {
    const found = live.items.find(i => (i.id || '').toUpperCase() === normalized);
    if (found) {
      const item = tier === 'enterprise' ? filterEnterprise(found)
                  : tier === 'pro'        ? filterPro(found)
                  : filterFree(found);
      return { found: true, item: attestItem(item) };
    }
  }
  return { found: false, item: null };
}

// Full-text search across live intel
function searchIntel(query, tier, params = {}) {
  const q = String(query || '').toLowerCase().trim();
  if (!q || q.length < 2) return { items: [], total: 0, query };
  const live = loadJSON(PATHS.live);
  if (!live || !live.items) return { items: [], total: 0, query };
  const matches = live.items.filter(item => {
    const text = [item.id, item.title, item.description, item.vendor, item.product, item.type]
      .join(' ').toLowerCase();
    return text.includes(q);
  });
  const { page, limit, offset } = parsePagination(params);
  const paged = matches.slice(offset, offset + limit);
  return {
    items:      applyTierFilter(paged, tier),
    total:      matches.length,
    query,
    pagination: { page, limit, total: matches.length, total_pages: Math.ceil(matches.length / limit) },
  };
}

// Platform stats (public — used by dashboard)
function getPlatformStats() {
  const state = loadJSON(PATHS.state) || {};
  const live  = loadJSON(PATHS.liveWidget) || {};
  const st    = live.stats || {};
  return {
    total_published:  state.totalPublished || 0,
    last_run:         state.lastRun || null,
    version:          state.version || '4.0',
    live_intel_count: (live.items || []).length,
    critical_threats: st.critical || 0,
    cisa_kev_count:   st.cisaKev  || 0,
    exploited_count:  st.exploited || 0,
    ransomware_count: st.ransomware || 0,
  };
}

module.exports = { getIntel, getCVEDetail, searchIntel, getPlatformStats, applyTierFilter };
