/**
 * SENTINEL APEX — Intelligence Hub Aggregation Engine
 * Pure, read-only aggregation over data the live ingestion pipeline
 * already generates (api/intel/products/*.json, api/intel/cve/*.json,
 * api/intel/campaigns.json). Never invents vendors, dates, CVEs, or
 * detection content — every output item traces back to a real generated
 * JSON file already on disk. Consumed by generate-intelligence-hub.js.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const PRODUCTS_DIR = path.resolve(__dirname, '../intel/products');
const CVE_DIR = path.resolve(__dirname, '../intel/cve');
const CAMPAIGNS_PATH = path.resolve(__dirname, '../intel/campaigns.json');

function loadProducts() {
  let files = [];
  try {
    files = fs.readdirSync(PRODUCTS_DIR).filter((f) => f.endsWith('.json'));
  } catch (_) {
    return [];
  }
  const out = [];
  for (const f of files) {
    try {
      const data = JSON.parse(fs.readFileSync(path.join(PRODUCTS_DIR, f), 'utf8'));
      out.push({ slug: f.slice(0, -5), ...data });
    } catch (_) {
      // Skip malformed/partial files rather than fail the whole aggregation.
    }
  }
  return out;
}

function loadCves() {
  let files = [];
  try {
    files = fs.readdirSync(CVE_DIR).filter((f) => f.endsWith('.json'));
  } catch (_) {
    return [];
  }
  const out = [];
  for (const f of files) {
    try {
      const data = JSON.parse(fs.readFileSync(path.join(CVE_DIR, f), 'utf8'));
      out.push({ slug: f.slice(0, -5), ...data });
    } catch (_) {
      // Skip malformed/partial files rather than fail the whole aggregation.
    }
  }
  return out;
}

function loadCampaigns() {
  try {
    const data = JSON.parse(fs.readFileSync(CAMPAIGNS_PATH, 'utf8'));
    return Array.isArray(data.campaigns) ? data.campaigns : [];
  } catch (_) {
    return [];
  }
}

// Known non-vendor `vendor` field values — citation sources and news
// outlets the ingestion pipeline stamps into `vendor` when no real
// affected-vendor is known (see fetch-live-intel.js rssToIntel()).
// Package-ecosystem names (npm, pip, go, composer, maven, ...) are
// intentionally NOT excluded — they are real, legitimate grouping
// entities for open-source supply-chain intelligence.
const NON_VENDOR_LABELS = new Set([
  'securityweek', 'bleepingcomputer', 'the hacker news', 'darkreading',
  'seclists', 'sans isc', 'isc', 'krebsonsecurity', 'wired_security',
  'unit42', 'reddit_cyber', 'reddit_netsec', 'threat intelligence',
  'cyberdudebivash', 'cyberdudebivash sentinel apex',
]);

function isRealVendor(vendor) {
  const v = String(vendor || '').trim();
  if (!v) return false;
  if (NON_VENDOR_LABELS.has(v.toLowerCase())) return false;
  if (/^reddit/i.test(v)) return false;
  return true;
}

function slugify(text) {
  const s = String(text || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return s || 'unknown';
}

/**
 * Real vendors/ecosystems, derived only from CVE records that already
 * carry a genuine `vendor` value — never inferred or invented. Each
 * vendor's items link back to the existing canonical /cve/{id}.html page
 * rather than duplicating any CVE content.
 */
function buildVendorIndex(cves, { minItems = 1 } = {}) {
  const groups = new Map();
  for (const cve of cves) {
    if (!isRealVendor(cve.vendor)) continue;
    const name = String(cve.vendor).trim();
    const key = slugify(name);
    if (!groups.has(key)) {
      groups.set(key, { slug: key, name, items: [] });
    }
    const id = cve.id || cve.slug;
    groups.get(key).items.push({
      id,
      title: cve.title || id,
      cvss: typeof cve.cvss === 'number' ? cve.cvss : null,
      threatLevel: cve.threat_level || null,
      cisaKev: !!cve.cisa_kev,
      exploited: !!cve.exploited,
      product: cve.product || null,
      url: `/cve/${id}.html`,
    });
  }
  const vendors = [...groups.values()]
    .filter((v) => v.items.length >= minItems)
    .map((v) => ({
      slug: v.slug,
      name: v.name,
      items: v.items,
      count: v.items.length,
      kevCount: v.items.filter((i) => i.cisaKev).length,
      exploitedCount: v.items.filter((i) => i.exploited).length,
      criticalCount: v.items.filter((i) => (i.cvss || 0) >= 9).length,
    }));
  vendors.sort((a, b) => b.count - a.count);
  return vendors;
}

/**
 * Real chronological feed of published intelligence — one entry per
 * product JSON already generated by the live ingestion pipeline. Links
 * to the existing canonical /posts/{slug}.html page.
 */
function buildTimeline(products, { limit = 300 } = {}) {
  const items = products
    .filter((p) => p.generated && p.title)
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      url: `/posts/${p.slug}.html`,
      generated: p.generated,
      severity: p.severity || null,
      cvss: typeof p.cvss === 'number' ? p.cvss : null,
      cves: Array.isArray(p.cves) ? p.cves : [],
      vendor: p.vendor || null,
      product: p.product || null,
      cisaKev: !!p.cisa_kev,
      exploited: !!p.exploited,
    }));
  items.sort((a, b) => new Date(b.generated) - new Date(a.generated));
  return items.slice(0, limit);
}

/**
 * Fixed, named topic collections. Each collection is a real, keyword-
 * matched subset of already-published intelligence — never a fabricated
 * or placeholder grouping. A collection with zero real matches is
 * omitted entirely rather than shown empty.
 */
const COLLECTION_DEFINITIONS = [
  {
    slug: 'ransomware-intelligence',
    name: 'Ransomware Intelligence Collection',
    description: 'Ransomware campaigns, extortion groups, and encryption/exfiltration incidents.',
    match: (p) => /ransomware|extortion|lockbit|akira|qilin|blackcat|alphv|black basta|scattered spider/i.test(`${p.title} ${p.product || ''}`),
  },
  {
    slug: 'ai-security-intelligence',
    name: 'AI Security & LLM Threat Collection',
    description: 'LLM security, prompt injection, AI agent risk, and AI governance coverage.',
    match: (p) => /\b(ai|llm|prompt injection|ai agent|genai|mcp)\b/i.test(`${p.title} ${p.product || ''}`),
  },
  {
    slug: 'supply-chain-intelligence',
    name: 'Supply Chain & Open-Source Security Collection',
    description: 'npm, PyPI, and other package-ecosystem compromises and dependency attacks.',
    match: (p) => /supply chain|\bnpm\b|\bpypi\b|dependency|malicious package|typosquat/i.test(`${p.title} ${p.product || ''}`),
  },
  {
    slug: 'nation-state-apt',
    name: 'Nation-State & APT Activity Collection',
    description: 'State-sponsored threat actor campaigns and advanced persistent threat tracking.',
    match: (p) => /\bapt\b|nation-state|state-sponsored|espionage|lazarus|volt typhoon|apt28|apt29/i.test(`${p.title} ${p.product || ''}`),
  },
  {
    slug: 'kev-actively-exploited',
    name: 'CISA KEV — Actively Exploited Collection',
    description: 'Vulnerabilities confirmed to be under active exploitation in the wild.',
    match: (p) => !!p.cisa_kev || !!p.exploited,
  },
  {
    slug: 'cloud-devsecops',
    name: 'Cloud & DevSecOps Security Collection',
    description: 'Cloud misconfigurations, container security, and DevSecOps pipeline risk.',
    match: (p) => /\bcloud\b|kubernetes|docker|container|ci\/cd|devsecops|\baws\b|\bazure\b|\bgcp\b/i.test(`${p.title} ${p.product || ''}`),
  },
];

function buildCollections(products, campaigns = []) {
  return COLLECTION_DEFINITIONS.map((def) => {
    const items = products
      .filter((p) => p.title && def.match(p))
      .sort((a, b) => new Date(b.generated || 0) - new Date(a.generated || 0))
      .map((p) => ({
        slug: p.slug,
        title: p.title,
        url: `/posts/${p.slug}.html`,
        generated: p.generated || null,
        severity: p.severity || null,
        cves: Array.isArray(p.cves) ? p.cves : [],
      }));
    const activeCampaigns = campaigns.filter((c) => def.match({ title: c.title || c.name || '', product: '' }));
    return {
      slug: def.slug,
      name: def.name,
      description: def.description,
      count: items.length,
      items,
      activeCampaigns,
    };
  }).filter((c) => c.count > 0);
}

/**
 * Live per-article detection content (Sigma/KQL/Splunk/OSQuery/Suricata)
 * already generated by the ingestion pipeline for individual reports,
 * aggregated into a single browsable feed. Distinct from, and additive
 * to, the hand-curated flagship rules in detections/rules/.
 */
function buildDetectionLibrary(products, { limit = 200 } = {}) {
  const items = products
    .filter((p) => p.detections && Object.values(p.detections).some((arr) => Array.isArray(arr) && arr.length > 0))
    .map((p) => ({
      slug: p.slug,
      title: p.title,
      url: `/posts/${p.slug}.html`,
      generated: p.generated || null,
      severity: p.severity || null,
      cves: Array.isArray(p.cves) ? p.cves : [],
      mitreAttack: Array.isArray(p.mitre_attack) ? p.mitre_attack : [],
      sigma: p.detections.sigma || [],
      kql: p.detections.kql || [],
      splunk: p.detections.splunk || [],
      osquery: p.detections.osquery || [],
      suricata: p.detections.suricata || [],
    }));
  items.sort((a, b) => new Date(b.generated || 0) - new Date(a.generated || 0));
  return items.slice(0, limit);
}

/**
 * Real published articles whose title matches `pattern` — used to give
 * the static threat-actor pages genuine, current cross-links instead of
 * stale hand-authored ones.
 */
function articlesMatching(products, pattern, { limit = 6 } = {}) {
  return products
    .filter((p) => p.title && pattern.test(p.title))
    .sort((a, b) => new Date(b.generated || 0) - new Date(a.generated || 0))
    .slice(0, limit)
    .map((p) => ({ slug: p.slug, title: p.title, url: `/posts/${p.slug}.html`, generated: p.generated || null }));
}

module.exports = {
  loadProducts, loadCves, loadCampaigns,
  isRealVendor, slugify,
  buildVendorIndex, buildTimeline, buildCollections, buildDetectionLibrary,
  articlesMatching,
  COLLECTION_DEFINITIONS, NON_VENDOR_LABELS,
};
