"""ASTRA Revenue Intelligence v18.1 — pre-compiler semantic alignment.

Production canary evidence from v18 showed that the continuation loop was using
``strict_yield_contract_complete`` while Stage-2 premium evidence compilation
certifies the *model-authored pre-compiler body* on exactly three analytical
axes: words, substantive paragraphs, and substantive list items. Canonical
section headings are renderer-owned and therefore must not consume continuation
budget or be regenerated by the model.

v18.1 changes only the continuation decision/targeting semantics:

* completion uses ``premium_evidence_compiler.compiler_semantic_preflight_complete``;
* continuation prompts target only word/paragraph/list deficits;
* continuation fragments containing headings are rejected because the compiler
  owns all headings;
* source-evidence admission, max passes, token budget, provider routing, paid
  policy, ReportX, Dossier v8, premium publication and Blogger fetch-back gates
  remain unchanged.

This is a yield-efficiency correction, never a gate relaxation.
"""
from __future__ import annotations

from collections import Counter
from typing import Any

from bs4 import BeautifulSoup

from . import astra_revenue_intelligence_v18 as _astra
from . import authority_transformer as _authority
from . import premium_evidence_compiler as _compiler
from . import premium_publication as _premium
from .logger import setup_logger

logger = setup_logger("astra_revenue_yield_alignment_v18_1")

MARKER = "CDB-ASTRA-REVENUE-YIELD-ALIGNMENT-V18.1"
_INSTALLED = False
_ORIGINAL_TELEMETRY = None

_RUNTIME = {
    "aligned_candidates": 0,
    "aligned_attempts": 0,
    "aligned_fragments": 0,
    "aligned_successes": 0,
    "provider_successes": Counter(),
    "skips": Counter(),
    "rejections": Counter(),
}


def _precompiler_metrics(content: str) -> dict[str, int]:
    paragraphs, list_items = _premium._semantic_counts(content or "")
    return {
        "words": int(_premium._word_count(content or "")),
        "paragraphs": int(paragraphs),
        "list_items": int(list_items),
    }


def _precompiler_complete(content: str) -> bool:
    return bool(_compiler.compiler_semantic_preflight_complete(content or ""))


def _aligned_continuation_prompt(original_prompt: str, existing: str, pass_index: int) -> str:
    metrics = _precompiler_metrics(existing)
    need_words = max(0, _premium.MIN_VISIBLE_WORDS - metrics["words"])
    need_paragraphs = max(0, _premium.MIN_PARAGRAPHS - metrics["paragraphs"])
    need_items = max(0, _premium.MIN_LIST_ITEMS - metrics["list_items"])
    source_context = (original_prompt or "")[-_astra.MAX_PROMPT_CHARS:]
    existing_context = (existing or "")[-_astra.MAX_EXISTING_BODY_CHARS:]

    return f"""{source_context}

ASTRA TARGETED CONTINUATION v18.1 — PRE-COMPILER ANALYTICAL-DENSITY RECOVERY
Return ONLY additional HTML body fragments for the existing public CTI dossier.
The deterministic Stage-2 compiler owns ALL report headings and References.

EXACT UNCHANGED PRE-COMPILER DEFICIT
- useful visible analytical words still required: {need_words}
- substantive paragraphs still required: {need_paragraphs}
- substantive list items still required: {need_items}

OUTPUT CONTRACT
- Emit NO <h1>, <h2>, <h3>, <h4>, <h5> or <h6> elements.
- Emit only evidence-specific <p>, <ul>/<ol>, <li>, and, when useful, bounded tables.
- Add only decision-useful depth supported by source evidence already supplied in this prompt.
- Prefer operationally distinct material: telemetry requirements, detection validation, hunt pivots,
  exposure validation, response decision criteria, remediation verification, collection gaps,
  executive decision conditions, or explicit unknowns.
- Do not restate existing paragraphs merely to increase length.
- Never invent an IOC, CVE property, ATT&CK mapping, exploitation state, affected version,
  patch/remediation fact, victim impact, attribution, statistic, customer exposure,
  customer compromise, regulatory applicability, or financial loss.
- If a material fact is absent, state "Not established in cited evidence." and identify the
  evidence/telemetry required to resolve it.
- Do not include References, report IDs, source hashes, prompts, drafting notes, token/word-count
  discussion, markdown fences, model reasoning, or system/developer/user instructions.

EXISTING MODEL-AUTHORED BODY — DO NOT REPEAT
{existing_context}
"""


def _safe_aligned_fragment(raw: str, existing: str) -> str | None:
    fragment = _astra._safe_continuation_fragment(raw, existing)
    if not fragment:
        return None
    soup = BeautifulSoup(fragment, "html.parser")
    if soup.find(["h1", "h2", "h3", "h4", "h5", "h6"]):
        _RUNTIME["rejections"]["renderer_owned_heading_emitted"] += 1
        return None
    return fragment


def aligned_astra_quality_aware_authority_llm(
    config,
    prompt: str,
    max_tokens: int = 3000,
    attempts=None,
    sleep_fn=None,
):
    """v18 continuation aligned with the Stage-2 pre-compiler gate."""
    if _astra._INNER_AUTHORITY_CALL is None or _astra._CONTINUATION_CALL is None:
        raise RuntimeError("ASTRA v18 base runtime is not installed")

    ledger = attempts if attempts is not None else []
    kwargs = {"max_tokens": max_tokens, "attempts": ledger}
    if sleep_fn is not None:
        kwargs["sleep_fn"] = sleep_fn
    result = _astra._INNER_AUTHORITY_CALL(config, prompt, **kwargs)
    if not result:
        _RUNTIME["skips"]["no_initial_generation"] += 1
        return result

    content, provider = result
    if _precompiler_complete(content):
        _RUNTIME["skips"]["initial_precompiler_contract_complete"] += 1
        return result

    article = _astra._active_article()
    if article is None:
        _RUNTIME["skips"]["no_active_article_context"] += 1
        return result
    if not _astra._source_evidence_sufficient(article):
        _RUNTIME["skips"]["insufficient_source_evidence"] += 1
        return result

    _RUNTIME["aligned_candidates"] += 1
    combined = content
    for pass_index in range(1, _astra.MAX_CONTINUATION_PASSES + 1):
        if _precompiler_complete(combined):
            break

        _RUNTIME["aligned_attempts"] += 1
        continuation_prompt = _aligned_continuation_prompt(prompt, combined, pass_index)
        continuation_result = _astra._CONTINUATION_CALL(
            config,
            continuation_prompt,
            max_tokens=_astra.CONTINUATION_MAX_TOKENS,
            attempts=ledger,
            sleep_fn=sleep_fn,
        )
        if not continuation_result:
            _RUNTIME["rejections"]["provider_unavailable"] += 1
            continue

        fragment_raw, continuation_provider = continuation_result
        fragment = _safe_aligned_fragment(fragment_raw, combined)
        if not fragment:
            continue

        combined = combined.rstrip() + "\n" + fragment
        _RUNTIME["aligned_fragments"] += 1
        _RUNTIME["provider_successes"][str(continuation_provider or "unknown")] += 1

        if _precompiler_complete(combined):
            _RUNTIME["aligned_successes"] += 1
            logger.info(
                "ASTRA v18.1 targeted continuation reached unchanged pre-compiler contract",
                extra={
                    "marker": MARKER,
                    "pass": pass_index,
                    "initial_provider": str(provider),
                    "continuation_provider": str(continuation_provider),
                    "metrics": _precompiler_metrics(combined),
                },
            )
            return combined, provider

    logger.warning(
        "ASTRA v18.1 continuation exhausted; downstream premium gate remains authoritative",
        extra={
            "marker": MARKER,
            "metrics": _precompiler_metrics(combined),
            "passes": _astra.MAX_CONTINUATION_PASSES,
        },
    )
    return combined, provider


def _aligned_telemetry_snapshot() -> dict:
    if _ORIGINAL_TELEMETRY is None:
        raise RuntimeError("ASTRA v18.1 telemetry is not installed")
    base = dict(_ORIGINAL_TELEMETRY())
    base["yield_alignment_v18_1"] = {
        "marker": MARKER,
        "completion_contract": "premium_evidence_compiler.compiler_semantic_preflight_complete",
        "renderer_owns_headings": True,
        "quality_floor_lowered": False,
        "max_passes": int(_astra.MAX_CONTINUATION_PASSES),
        "max_tokens_per_pass": int(_astra.CONTINUATION_MAX_TOKENS),
        "aligned_candidates": int(_RUNTIME["aligned_candidates"]),
        "aligned_attempts": int(_RUNTIME["aligned_attempts"]),
        "aligned_fragments": int(_RUNTIME["aligned_fragments"]),
        "aligned_successes": int(_RUNTIME["aligned_successes"]),
        "provider_successes": dict(_RUNTIME["provider_successes"]),
        "skips": dict(_RUNTIME["skips"]),
        "rejections": dict(_RUNTIME["rejections"]),
        "telemetry_contains_prompts": False,
        "telemetry_contains_response_content": False,
        "telemetry_contains_credentials": False,
    }
    return base


def install_astra_revenue_yield_alignment_v18_1() -> None:
    global _INSTALLED, _ORIGINAL_TELEMETRY
    if _INSTALLED:
        return
    if _astra._INNER_AUTHORITY_CALL is None:
        raise RuntimeError("ASTRA v18 must be installed before v18.1 alignment")

    _ORIGINAL_TELEMETRY = _astra.telemetry_snapshot
    _authority.call_llm = aligned_astra_quality_aware_authority_llm
    _astra.telemetry_snapshot = _aligned_telemetry_snapshot

    if _authority.call_llm is not aligned_astra_quality_aware_authority_llm:
        raise RuntimeError("ASTRA v18.1 failed to bind aligned authority runtime")
    if (
        _premium.MIN_VISIBLE_WORDS != 2200
        or _premium.MIN_DISTINCT_HEADINGS != 18
        or _premium.MIN_PARAGRAPHS != 18
        or _premium.MIN_LIST_ITEMS != 18
    ):
        raise RuntimeError("ASTRA v18.1 refuses installation because the authoritative public quality floor changed")

    _INSTALLED = True
    logger.info(
        "ASTRA Revenue Intelligence v18.1 pre-compiler yield alignment installed",
        extra={
            "marker": MARKER,
            "completion_contract": "compiler_semantic_preflight_complete",
            "renderer_owns_headings": True,
            "quality_floor_lowered": False,
        },
    )
